name: Go

on:
    push:
        branches: [ master ]
    pull_request:
    schedule:
        - cron: "0 0 * * *"

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                go: ['1.19', '1.20', '1.21', '1.x']

        steps:
            - name: Build packages
              run: go build -v ./...
              working-directory: go/src/github.com/openconfig/gnoigo

            - name: Run Tests
              run: go test -v ./...
              working-directory: go/src/github.com/openconfig/gnoigo