name: Go

on:
    push:
        branches: [ main ]
    pull_request:
    schedule:
        - cron: "0 0 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Go
              uses: actions/setup-go@v2.1.3
              with:
                go-version: 1.21.x
            - name: Build
              run: go build -v ./...
            - name: Run Tests
              run: go test -v ./...
