name: Go

on:
    push:
        branches: [ master ]
    pull_request:
    schedule:
        - cron: "0 0 * * *"

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                go: ['1.x']

        steps:
            - name: Build packages
              run: go build -v ./...

            - name: Run Tests
              run: go test -v ./...
